version: '3'
services:
  api :
    container_name: xiaozhu-api
    restart: always
    ports:
      - '8889:8889'
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      TZ: 'Asia/Shanghai'
    volumes:
      - '${PWD}/api/etc:/app/xiaozhu-api/etc' #配置文件
      - '${PWD}/api/storage:/app/xiaozhu-api/storage' #日志、上传等静态文件
    command: './xiaozhu-api'
